### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by jingjingzhao** [MAXLZ1/micro-app-demos#1]
![image](https://user-images.githubusercontent.com/5880014/197097288-29d2e237-a6dd-4c31-9f9d-59b5093ab892.png)

**Comment by MAXLZ1** [comment]
删除import {process} from ‘node’这一行

**Comment by jingjingzhao** [comment]
上面截图错了。是这个报错
![image](https://user-images.githubusercontent.com/5880014/197099585-29ac8b5f-1e24-43a7-8f09-f02ad47c1be1.png)

**Comment by MAXLZ1** [comment]
安装下@types/node
`pnpm —filter ./packages/qiankun-demo/vue2-child add @types/node - D`

**Comment by jingjingzhao** [comment]
安装了，一样的报错

**Comment by MAXLZ1** [comment]
如果还报错，tsconfig.json的type添加node

**Comment by jingjingzhao** [comment]
那个报错没有了，下一个报错
![image](https://user-images.githubusercontent.com/5880014/197101898-020e007a-5b89-4996-98ac-cb3256407db4.png)

**Comment by MAXLZ1** [comment]
本地没有报错，这个添加@ts-ignore吧

**Comment by jingjingzhao** [comment]
一个一个解决了。还是有报错。我还是直接看源码，解决我的问题吧
![image](https://user-images.githubusercontent.com/5880014/197103758-2a82bff5-6a1f-419f-8137-3fc0808f4b9a.png)
![image](https://user-images.githubusercontent.com/5880014/197103772-867ec210-1e6e-44eb-889b-137e81b7356c.png)

**Comment by jingjingzhao** [comment]
我是Mac，`pnpm --stream run qiankun-demo:start` 可以运行起来了。但只能启动起来 vue2-child和react-child。主应用和另一个子应用没起来 
![image](https://user-images.githubusercontent.com/5880014/197126581-ffd074db-f64a-421b-9ed9-3da6ddfa4acb.png)

**Comment by MAXLZ1** [comment]
`pnpm --filter "@qiankun-demo/*" -r --stream run start`
主应用和另一个子应用都是vite项目，启动日志在最前面，试试`http://localhost:8081`能不能正常访问

**Comment by jingjingzhao** [comment]
可以啦~感谢大佬
