### ISSUE TITLE
请问如何进行微应用缓存，有点没太看懂

### ISSUE THREAD

**Issue by NINGyv179** [MAXLZ1/micro-app-demos#2]
![image](https://user-images.githubusercontent.com/56420939/204433582-3e934251-a1eb-4086-a935-9a2a7c64cd1b.png)

**Comment by MAXLZ1** [comment]
利用vue的keep-alive进行缓存，实现思路就是在主应用中新建一个页面用来展示子应用的某个页面，然后将这个页面添加到keep-alive的include中。这样做的缺点就是，对于每个子应用需要缓存的页面都需要在主应用新建一个页面。

**Comment by NINGyv179** [comment]
> 利用vue的keep-alive进行缓存，实现思路就是在主应用中新建一个页面用来展示子应用的某个页面，然后将这个页面添加到keep-alive的include中。这样做的缺点就是，对于每个子应用需要缓存的页面都需要在主应用新建一个页面。

我试了一下，但是每次都是会重新请求，难道是因为我没用loadMicroApp，而是用registerMicroApps的原因

**Comment by MAXLZ1** [comment]
用loadMicroApp加载可以，registerMicroApps会根据url的变化进行加载。
https://github.com/MAXLZ1/micro-app-demos/blob/b4547c1b50754b7f453e1970353bb8ac7b35b574/packages/qiankun-demo/vue3-main/src/views/React18KeepAliveView.vue#L20-L29
